### PR TITLE
Add support for Python 3.9

### PR DESCRIPTION
**Pull request by hugovk**

### CODE REVIEW

**Comment by hugovk** [comment]
Might be a good time to review whether to drop any of the EOL versions: 2.7, 3.4, 3.5?



Here's the pip installs for twitter from PyPI for October 2020:

| category | percent | downloads |
|----------|--------:|----------:|
| 3.7      |  74.13% |    80,248 |
| 3.8      |  12.39% |    13,413 |
| null     |   5.93% |     6,423 |
| 3.6      |   5.93% |     6,416 |
| 2.7      |   1.21% |     1,310 |
| 3.5      |   0.21% |       224 |
| 3.9      |   0.19% |       203 |
| 3.4      |   0.01% |         6 |
| 3.10     |   0.00% |         2 |
| 3.3      |   0.00% |         1 |
| Total    |         |   108,246 |

Source: `pip install -U pypistats && pypistats python_minor twitter --last-month`

**Comment by RouxRC** [comment]
I agree with removing 3.4 which is such a weird python version anyway. 3.5 could probably make sense as well.
But 2.7 is still not completely disappeared it seems, and since the code has been kept compatible, I would continue keeping it a bit longer?

**Comment by RouxRC** [comment]
Travis seems a bit overloaded since a few weeks https://www.traviscistatus.com/#month
I guess the tests will be finished by tomorrow, I'll check back then

**Comment by hugovk** [comment]
Yeah, Travis is a bit of a mess!

Travis-ci.org has been scaled down, will shut down at the end of the year and all projects must migrate to .com:

https://docs.travis-ci.com/user/migrate/open-source-repository-migration#frequently-asked-questions

But they have a new pricing model which places limits on OSS, and there's still many unknowns:

https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing

http://www.jeffgeerling.com/blog/2020/travis-cis-new-pricing-plan-threw-wrench-my-open-source-works

I recommend moving to GitHub Actions. I can open a PR later for this.

**Comment by RouxRC** [comment]
Ha I missed those announcements, good to know, thanks!
Migrating to Github Actions makes sense to me, that's great if you can do a PR for this!

**Pull request merged**
